import java.util.*;
class GuessNo {
    public static void main(String[] args) {
        Scanner sc=new Scanner(System.in);
        char ch='Y';//to continue the game again
        int cnt=6;//max number of attempts to guess the number 
        while(ch=='Y'){
            int c=0;
        int R=(int)(Math.random()*100);//multiply generated random number with specified number within which number you want to generate number from 1.If you want to generate a number b/w 50 to 100 check whether R>=50 if not once again generate a number and repeat same process till you get required number.
        while(1==1){
            if(c==0){
        System.out.print("enter a number to guess the number generated by system(B/W 1 to 100):");}
        else {System.out.print("Try Again:");}
        int n=sc.nextInt();
        if(n==R){System.out.print("your guess is correct.\n");break;}
        else if(n>R){System.out.print("your guess is too high.\n");}
        else {System.out.print("Your guess is too low.\n");}
         c+=1;
         if(c==cnt){System.out.print("You chances are completed.");break;
    }}if(c!=cnt)System.out.print("You guessed the number in "+c+" rounds.");
    System.out.print("Do you want to play again? Y/N:");
    ch =sc.next().charAt(0);
    if(ch=='N'){System.out.println("---------------THANK YOU---------------");
        System.out.println("-----------------VISIT AGAIN-----------------");
    }
    }
    }
}
